import { DEFAULT_CONFIG } from "./constants.js";

export const PRESETS = [
  {
    name: "sUSDe → GHO",
    config: DEFAULT_CONFIG,
  },
  {
    name: "weETH → USDC",
    config: {
      strategyName: "weETH Loop → USDC Exit",
      loopChain: "Base",
      collateralAsset: "weETH",
      borrowAsset: "WETH",
      exitChain: "Base",
      exitAsset: "USDC",
      collateralSupplyApy: 3.20,
      borrowApy: 2.80,
      exitSupplyApy: 5.50,
      maxLtv: 80,
      safetyBuffer: 10,
      capital: 10000,
      benchmarkApy: 5.50,
      benchmarkLabel: "USDC Direct Supply",
      stressCollateral: 24400,
      stressDebt: 14400,
      stressLiqThreshold: 82,
    },
  },
  {
    name: "wstETH → DAI",
    config: {
      strategyName: "wstETH Loop → DAI Exit",
      loopChain: "Ethereum",
      collateralAsset: "wstETH",
      borrowAsset: "ETH",
      exitChain: "Ethereum",
      exitAsset: "DAI",
      collateralSupplyApy: 4.10,
      borrowApy: 3.20,
      exitSupplyApy: 6.00,
      maxLtv: 80,
      safetyBuffer: 10,
      capital: 10000,
      benchmarkApy: 6.00,
      benchmarkLabel: "DAI DSR",
      stressCollateral: 24400,
      stressDebt: 14400,
      stressLiqThreshold: 82,
    },
  },
  {
    name: "USDC Simple",
    config: {
      strategyName: "USDC Loop → USDT Exit",
      loopChain: "Arbitrum",
      collateralAsset: "USDC",
      borrowAsset: "USDT",
      exitChain: "Arbitrum",
      exitAsset: "USDT",
      collateralSupplyApy: 4.50,
      borrowApy: 3.80,
      exitSupplyApy: 5.20,
      maxLtv: 90,
      safetyBuffer: 5,
      capital: 10000,
      benchmarkApy: 5.20,
      benchmarkLabel: "USDT Direct Supply",
      stressCollateral: 24400,
      stressDebt: 14400,
      stressLiqThreshold: 93,
    },
  },
];
